### ISSUE TITLE
Communication problem when using map.flyTo() method

### ISSUE THREAD

**Issue by peterklima** [mstahv/v-leaflet#111] opened 2016-01-21 12:30 UTC
I have following problem, when "flying between markers". Please see the attached screen shot of the error message (and its JSON). Maybe the "zoomLevel: NaN" is the Problem?

Thanks in advance.

KR Peter

![screen shot 2016-01-21 at 13 27 53](https://cloud.githubusercontent.com/assets/1203988/12480483/eef30cf4-c042-11e5-9cfb-6b73bef982c2.png)

**Comment by mstahv** [comment] 2016-01-24 09:37
Hi, Peter!

I'd say a good guess. Could you share a small code snippet how the issue can be reproduced? That would help a lot to find out why the bug appears and how to fix it properly.

**Comment by peterklima** [comment] 2016-01-25 07:28
Hi, thanks for the fast answer.

I have attached my sample code. To reproduce just click the buttons to use the flyTo-method. (I noticed the bug only occurs when the zoom-animation is completed, otherwise it's working!)

KR Peter

```java
package com.hoodsider.views.home;

import org.vaadin.addon.leaflet.LMap;
import org.vaadin.addon.leaflet.LTileLayer;
import org.vaadin.addon.leaflet.shared.Point;

import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class MapView extends VerticalLayout {

	public MapView() {
		setSizeFull();

		final LMap map = new LMap();
		LTileLayer layer = new LTileLayer("http://{s}.tiles.mapbox.com/v3/secret/{z}/{x}/{y}.png");
		layer.setDetectRetina(true);
		map.addLayer(layer);
		map.setSizeFull();
		addComponent(map);

		HorizontalLayout toolbar = new HorizontalLayout();
		addComponent(toolbar);

		Button buttonVienna = new Button("Fly to Vienna");
		toolbar.addComponent(buttonVienna);
		buttonVienna.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				map.flyTo(new Point(48.2085, 16.3721), 10d));
			}
		});

		Button buttonHelsinki = new Button("Fly to Helsinki");
		toolbar.addComponent(buttonHelsinki);
		buttonHelsinki.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				map.flyTo(new Point(60.1724, 24.9423), 10d));
			}
		});
	}

}
```

**Comment by mstahv** [comment] 2016-01-25 07:46
This is actually reproducible with the test I initially used to develop the feature. I wonder why I missed that. I'll try to look into this later today.

**Comment by mstahv** [comment] 2016-01-25 19:16
I got it now. It seems to be a regression in Vaadin 7.6. I downgraded the project to 7.5.10 and it works. I'll file a bug to dev.vaadin.com

**Comment by mstahv** [comment] 2016-01-25 19:30
This is most likely the same issue as this: https://dev.vaadin.com/ticket/19447 

Hopefully will be fixed in 7.6.2 that will be released soon.

**Comment by mstahv** [comment] 2016-01-26 07:36
I played a bit with this and adding following small hack to g-leaflet's getZoom seems to be a workaround for this issue.

	public native final double getZoom()
	/*-{
            return this.getZoom()*1;
 	}-*/;

**Comment by peterklima** [comment] 2016-01-26 11:23
ok thanks, are you releasing a new version with this hack?

**Comment by mstahv** [comment] 2016-01-26 11:26
I probably will. Will need to take another thing as well before cutting a new release.

**Comment by mstahv** [comment] 2016-01-26 17:52
The change for the workaround is now in g-leaflet, will be fixed in next v-leaflet version.

**Closed by mstahv** 2016-01-26 17:52 UTC

**Comment by mstahv** [comment] 2016-01-27 16:09
The latest version now contains the fix, let me know if it don't work!

**Comment by peterklima** [comment] 2016-01-27 16:43
After upgrading to v-leaflet 1.0.0-b6 the issue remains. I noticed that g-leaflet is still on 1.0.0-b5?!

**Comment by mstahv** [comment] 2016-01-27 17:08
Are you sure you recompiled your widgetset? "mvn clean install" if using Maven and forced refresh your browser?

g-leaflet is one running beta release behind.

**Comment by peterklima** [comment] 2016-01-27 20:36
That's a pretty good hint ;) Thank you!
