### ISSUE TITLE
Overlay control missing in Firefox, overlay control icon missing in Chrome

### ISSUE THREAD

**Issue by dominic-simplan** [mstahv/v-leaflet#162] opened 2017-09-25 14:28 UTC
Hi,

first of all, thanks for the 1.0.4 update, using FontAwesome Icons in Markers and controlling their appearence is, well, awesome!

However, after upgrading to 1.0.4, there is no overlay control visible in Firefox anymore:
![grafik](https://user-images.githubusercontent.com/22240239/30813658-4de686f6-a20e-11e7-82ac-769b213a9593.png)

In Google Chrome, the overlay control is displayed and usable, but the icon is missing:
![grafik](https://user-images.githubusercontent.com/22240239/30813576-15d37896-a20e-11e7-91f8-d81f9f6a6934.png)

I used the LayerGroupTest for testing.
Is this a bug or do I need some additional configuration?

**Comment by basisbit** [comment] 2017-11-28 13:54
can not reproduce. Check in your browsers developer tools what is causing that issue. Any warnings in the console or similar? Maybe this is caused by some part of your CSS?

**Comment by dominic-simplan** [comment] 2017-11-28 14:27
No warning in the developer tools. And I only cloned this v-leaflet repository, checkout out branch 1.0.4, started the UIRunner and opened the LayerGroupTest, so no own CSS involved.
This is the element for the layers:
`<a class="leaflet-control-layers-toggle" href="#" title="Layers"></a>`
No image in the HTML or CSS defined, so I guess that's why it's white. Is it different for you?

**Comment by dominic-simplan** [comment] 2017-12-05 11:20
@basisbit Anything other information I could provide?

**Comment by ssteinke** [comment] 2018-01-22 10:20
Same here. It looks like the css for the background-image gets lost somewhere between leaflet, g-leaflet and v-leaflet. As a workaround, I've added this to my theme scss and copied the layers.png file from g-leaflet to an images directory in my theme.. Tested with Firefox, Chrome and Safari.
```
.v-leaflet{
	.leaflet-control-layers-toggle {
		width: 44px;
		height: 44px;
		background-position: 50% 50%;
		background-repeat: no-repeat;
		display: block;
	  	background-image: url(images/layers.png);
		background-size: 30px 30px;
	}
}
```
Is this connected to [this commit in g-leaflet](https://github.com/mstahv/g-leaflet/commit/dcd55307fdc04365979f1a476a74c556a1c84af3)?

**Comment by dominic-simplan** [comment] 2018-01-22 10:42
Just upgraded to Vaadin 8, same issue exists with v-leaflet 2.0.2

**Comment by octavm** [comment] 2018-02-12 11:43
I have created a [pull request](https://github.com/mstahv/g-leaflet/pull/55) with the fix needed in g-leaflet.
No need for any workaround. It was due to wrong line comment in leaflet.css which was causing the whole block to be commented out.

**Comment by mstahv** [comment] 2018-02-26 08:50
This should be now fixed.

**Closed by mstahv** 2018-02-26 08:50 UTC
